### ISSUE TITLE
faulty notification when not authenticated to private tracker

### ISSUE THREAD

**Issue by Pafzedog** [DASPRiD/Torrent-to-Web#11]
Sometimes I browse my favorite private tracker but I'm not authenticated,  I want to send a torrent to my seed box and I got all three notifications (retrieving, uploading and torrent file uploaded) but it's not right obviously, nothing is downloaded nor uploaded...
btw , thanks for this great extension :)

**Comment by DASPRiD** [comment]
That is kinda weird. I suppose the tracker you are using is not sending an "unauthenticated" status code in that case, but a successful response. In that case the addon would download whatever the tracker serves instead and upload that to your torrent client (which then would most likely reject the file silently, since it isn't a torrent file). Not too sure how to deal with that.

**Comment by DASPRiD** [comment]
This was resolved through #27
