### ISSUE TITLE
[Request] Android Support

### ISSUE THREAD

**Issue by zero77** [DASPRiD/Torrent-to-Web#32]
Can you please add support to run this in FireFox for android.

**Comment by felfert** [comment]
I'm afraid that's currently next to impossible, because (according to [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Differences_between_desktop_and_Android) doc) FF-Android has **no support** for augmenting context menus. If you have an idea how to accomplish the same functionality **without** a custom context-menu entry, please say so.

**Comment by zero77** [comment]
@felfert 
Would clipboard monitoring be an option as i think this is supported in android.

**Comment by felfert** [comment]
Not really. Users have to be able to decide for each link if they want to download and send it to their torrent client. After my PR #28 is merged, I **might** be able to handle something like that.

**Comment by DASPRiD** [comment]
@felfert Do you still plan to work on this?

**Comment by felfert** [comment]
> @felfert Do you still plan to work on this?

No. I have given up on that after some experiments.

**Comment by DASPRiD** [comment]
Closing this for now.
