### ISSUE TITLE
Vuze support, web remote or other implementation?

### ISSUE THREAD

**Issue by graycatgrayhat** [DASPRiD/Torrent-to-Web#5]
Would be great to see support for Vuze and the default implementation of their remote/web access protocol.

Vuze 5.7.5.0 
Vuze Web Remote 0.6.5

**Comment by felfert** [comment]
Vuze already works, because it uses the same protocol like Transmission.
I just tested it locally with Vuze/Azureus 5.7.6.0 and Vuze Web Remote 0.6.5 and had success.

### In the addon preferences, use the following values:

**Client**: ```Transmission```
**URL**: ```http://localhost:9091```
**Username**: ```vuze```
**Password**: _The pairing code, displayed in vuze_
